version: "3"

services:

  app:
    container_name: help_work_bot
    build: hwb/

    environment:
      TOKEN: "${TOKEN}"

    volumes:
      - $PWD/db/sqlite:/app/db/sqlite
      - $PWD/static:/app/static
      - $PWD/temp:/app/temp

  sqlite:
    image: coleifer/sqlite-web:latest
    container_name: sqlite
    ports:
      - "8080:8080"
    volumes:
      - $PWD/db/sqlite:/data
    environment:
      SQLITE_DATABASE: "command.db"

  redis:
    image: redis:7.0.4-alpine
    container_name: redis7
    ports:
      - "6379:6379"
    volumes:
      - $PWD/db/pyredis/redis_snapshot:/data
      - $PWD/db/pyredis/config/redis.conf:/usr/local/etc/redis/redis.conf
