version: "3"

services:

  app:
    container_name: help_work_bot
    build: hwb/

    environment:
      TOKEN: "${TOKEN}"

    volumes:
      - ./db/sqlite:/app/db/sqlite
      - ./static:/app/static
      - ./temp:/app/temp

  sqlite:
    image: coleifer/sqlite-web:latest
    container_name: sqlite
    ports:
      - "8080:8080"
    volumes:
      - ./db/sqlite:/data
    environment:
      SQLITE_DATABASE: "command.db"
