version: "3"

services:

  app:
    container_name: "${APP_CONTAINER_NAME}"
    build: hwb/

    environment:
      TOKEN: "${TOKEN}"
      DB: "${DB}"

    volumes:
      - $PWD/db/sqlite:/app/db/sqlite
      - $PWD/static:/app/static
      - $PWD/temp:/app/temp
      - $PWD/log:/app/log

  sqlite:
    image: coleifer/sqlite-web:latest
    container_name: "${SQLITE_CONTAINER_NAME}"
    ports:
      - "${SQLITE_PORTS}"
    volumes:
      - $PWD/db/sqlite:/data
    environment:
      SQLITE_DATABASE: "command.db"

  redis:
    image: redis:7.0.4-alpine
    container_name: "${REDIS_CONTAINER_NAME}"
    ports:
      - "${REDIS_CONTAINER_PORTS}"
    volumes:
      - $PWD/db/pyredis/redis_snapshot:/data
      - $PWD/db/pyredis/config/redis.conf:/etc/redis/redis.conf
