[tool.poetry]
name = "hwb"
version = "0.1.0"
description = ""
authors = [" tmutarakan  <ratibor.tmutarakansky@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^2.21"
rich = "^12.4.4"
flake8 = "^5.0.0"
redis = "^4.3.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
